#!/usr/bin/env bash
# Crop a screenshot from my dual monitor setup and reduce it to 1080p from 4k.

set -euo pipefail

F="$1"
EXT="${F##*.}"

convert "$F" -crop 3840x2160+0+0 -resize 1920x1080 "$F.resized.$EXT"
