#!/usr/bin/env bash
# TODO: genericize to any application
set -e
set -o pipefail

print_usage() {
  cat <<EOF
$0 URL

Open URL in a new tab if Firefox is open in the current workspace or
a new window if it is not.
EOF
}

firefox_is_open() {
  i3-save-tree | grep Firefox >/dev/null 2>/dev/null
}

focus_firefox() {
  i3-msg '[class="^Firefox$" workspace="__focused__"] focus'
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  if (( "$#" == 0 )); then
    print_usage
    exit 0
  fi

  if firefox_is_open; then
    focus_firefox
    firefox -new-tab "$@"
  else
    firefox -new-window "$@"
  fi
fi
