#!/usr/bin/env bash
# Very simple memorable password generator. Not recommended for anything needing
# real security.

WORDS=/usr/share/dict/words

randword() {
  shuf -n 1 $WORDS
}

randpunct() {
  </dev/urandom tr -dc '[:punct:]' | head -c "$1"
}

randnum() {
  </dev/urandom tr -dc '[:digit:]' | head -c "$1"
}

echo "$(randword)$(randnum 4)$(randpunct 2)$(randword)"
